on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: run the action
        id: hello 
        uses: ./
        with: 
          myInput: 'aldridge-s'
      - name: output
        run: |
          echo ${{ steps.outputs.memory }}
          echo "total memory successfully output"
